spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product?useSSL=false
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      use-new-id-generator-mappings: 'false'
      ddl-auto: create-drop
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

application:
  bucket:
    name: ea-final-project-bucket

cloud:
  aws:
    region:
      static: us-east-1
    stack:
      auto: false
    credentials:
      accessKey: ${AWSAccessKeyId}
      secretKey: ${AWSSecretKey}
#spring.jpa.hibernate.use-new-id-generator-mappings=false
#logging.level.root=WARN